name: csharp unit tests

on:
  pull_request:
    paths: [ 'src/csharp/**' ]
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd src/csharp/
        dotnet restore
    - name: Build
      run: |
        cd src/csharp/
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd src/csharp/
        dotnet test --no-restore --verbosity normal
