name: ruby unit tests

on:
  pull_request:
    paths: [ 'src/ruby/**' ]
    branches: [ dev, main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run tests
      run: |
        cd src/ruby/
        rake test
